## docker-compose.yml

version: "3.9"

services:
  web:
    build: . 
    container_name: a3
    ports:
      - "80:3000"
    volumes:
      - ./:/app
    command: ["node", "server.js"]

#    stdin_open: true
#    tty: true
